# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 15:13
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoggerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('project', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('usergroup', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('category', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('field', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('location', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('observation', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('comment', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('mediafile', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('subset', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('action', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('historical', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
