# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 15:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('projects', '0002_auto_20180328_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInteractionPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_to_post', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('status',
                 models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive')], default=b'active',
                                  max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialinteractions_post',
                                   to='projects.Project')),
                ('socialaccount',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialinteractions_post',
                                   to='socialaccount.SocialAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SocialInteractionPull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_to_pull', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(
                    choices=[(b'5min', b'5min'), (b'10min', b'10min'), (b'20min', b'20min'), (b'30min', b'30min'),
                             (b'hourly', b'hourly'), (b'daily', b'daily'), (b'weekly', b'weekly'),
                             (b'fortnightly', b'fortnightly'), (b'monthly', b'monthly')], default=b'daily',
                    max_length=20)),
                ('status',
                 models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive')], default=b'active',
                                  max_length=20)),
                ('since_id', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialinteractions_pull',
                                   to='projects.Project')),
                ('socialaccount',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socialinteractions_pull',
                                   to='socialaccount.SocialAccount')),
            ],
        ),
    ]
