# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 16:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    # replaces = [(b'projects', '0001_initial'),
    #             (b'projects', '0002_auto_20150106_1338'),
    #             (b'projects', '0003_auto_20150123_1148'),
    #             (b'projects', '0004_auto_20150123_1507'),
    #             (b'projects', '0005_auto_20150202_1041'),
    #             (b'projects', '0006_remove_admins_contact'),
    #             (b'projects', '0007_auto_20160122_1409'),
    #             (b'projects', '0008_historicalproject')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['project__name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isprivate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('everyone_contributes', models.CharField(choices=[(b'true', b'true'), (b'auth', b'auth'), (b'false', b'false')], default=b'auth', max_length=20)),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive'), (b'deleted', b'deleted')], default=b'active', max_length=20)),
                ('geographic_extend', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('admins', models.ManyToManyField(related_name='admins', through='projects.Admins', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='admins',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_of', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='admins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_admins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='admins',
            unique_together=set([('project', 'user')]),
        ),
        migrations.RunSQL(
            sql="DELETE FROM projects_admins WHERE project_id IN (SELECT id FROM projects_project WHERE status = 'deleted');",
        ),
        migrations.RemoveField(
            model_name='admins',
            name='contact',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='geographic_extend',
            new_name='geographic_extent',
        ),
        migrations.AddField(
            model_name='project',
            name='islocked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('isprivate', models.BooleanField(default=False)),
                ('islocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('everyone_contributes', models.CharField(choices=[(b'true', b'true'), (b'auth', b'auth'), (b'false', b'false')], default=b'auth', max_length=20)),
                ('status', models.CharField(choices=[(b'active', b'active'), (b'inactive', b'inactive'), (b'deleted', b'deleted')], default=b'active', max_length=20)),
                ('geographic_extent', django.contrib.gis.db.models.fields.PolygonField(geography=True, null=True, srid=4326)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical project',
            },
        ),
    ]
